### ISSUE TITLE
SciJava kernel not starting

### ISSUE THREAD

**Issue by geekSiddharth** [scijava/scijava-jupyter-kernel#75]
Default kernel:-

 `scijava    C:\Users\Sid\AppData\Roaming\jupyter\kernels\scijava`

And the install Scijava Kernel options are different: 
![image](https://user-images.githubusercontent.com/21156678/27766048-1f541288-5ee1-11e7-806c-9cc2becd56cb.png)

When I start a jupyter notebook with Scijava selected as the language, the kernel doesn't starts.

```
ernelRestarter: restarting kernel (3/5)
C:\Users\Sid\Anaconda3\lib\site-packages\IPython\kernel\__init__.py:13: ShimWarning: The `IPython.kernel` package has been deprecated since IPython 4.0.You should import from ipykernel or jupyter_client instead.
  "You should import from ipykernel or jupyter_client instead.", ShimWarning)
Traceback (most recent call last):
  File "C:\Users\Sid\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\Sid\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Sid\Anaconda3\lib\site-packages\octave_kernel.py", line 4, in <module>
    from oct2py import Oct2PyError, octave
  File "C:\Users\Sid\Anaconda3\lib\site-packages\oct2py\__init__.py", line 48, in <module>
    lib1 = ctypes.CDLL(os.path.join(basepath, 'core', 'libmmd.dll'))
  File "C:\Users\Sid\Anaconda3\lib\ctypes\__init__.py", line 347, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found
Exception in thread "main" java.lang.IllegalArgumentException: Invalid service: net.imagej.itk.DefaultImageJItkService
        at org.scijava.service.ServiceHelper.createExactService(ServiceHelper.java:280)
        at org.scijava.service.ServiceHelper.loadService(ServiceHelper.java:231)
        at org.scijava.service.ServiceHelper.loadService(ServiceHelper.java:194)
        at org.scijava.service.ServiceHelper.loadServices(ServiceHelper.java:166)
        at org.scijava.Context.<init>(Context.java:278)
        at org.scijava.Context.<init>(Context.java:234)
        at org.scijava.Context.<init>(Context.java:131)
        at org.scijava.Context.<init>(Context.java:118)
        at org.scijava.Context.<init>(Context.java:107)
        at org.scijava.jupyter.kernel.ScijavaKernel.main(ScijavaKernel.java:105)
Caused by: java.lang.UnsatisfiedLinkError: no SimpleITKJava in java.library.path
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
        at java.lang.Runtime.loadLibrary0(Runtime.java:870)
        at java.lang.System.loadLibrary(System.java:1122)
        at net.imagej.itk.DefaultImageJItkService.initialize(DefaultImageJItkService.java:87)
        at org.scijava.service.ServiceHelper.createServiceRecursively(ServiceHelper.java:353)
        at org.scijava.service.ServiceHelper.createExactService(ServiceHelper.java:269)
        ... 9 more
```

**Comment by geekSiddharth** [comment]
Thanks for the reply! :D 
What do you mean by  "Anaconda classpath with the one in your Fiji installation"?

**Comment by imagejan** [comment]
@hadim wrote:
> You are missing the Anaconda classpath with the one in your Fiji installation.

You meant "mixing" instead of "missing", right?

**Comment by hadim** [comment]
Yes mixing of course! Sorry for the confusion and thank you @imagejan .

**Comment by geekSiddharth** [comment]
@hadim This is what I got after keeping the "Additional JAVA classpath" empty.

```[I 20:19:38.975 NotebookApp] Kernel started: 1d8854e5-3392-440e-a7af-775675be5a79
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/C:/Users/Sid/Desktop/fiji-win64/Fiji.app/jars/logback-classic-1.2.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/C:/Users/Sid/Desktop/fiji-win64/Fiji.app/jars/slf4j-simple-1.7.25.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
[W 20:19:49.959 NotebookApp] Timeout waiting for kernel_info reply from 1d8854e5-3392-440e-a7af-775675be5a79
Exception in thread "main" java.lang.IllegalArgumentException: Invalid service: net.imagej.itk.DefaultImageJItkService
        at org.scijava.service.ServiceHelper.createExactService(ServiceHelper.java:280)
        at org.scijava.service.ServiceHelper.loadService(ServiceHelper.java:231)
        at org.scijava.service.ServiceHelper.loadService(ServiceHelper.java:194)
        at org.scijava.service.ServiceHelper.loadServices(ServiceHelper.java:166)
        at org.scijava.Context.<init>(Context.java:278)
        at org.scijava.Context.<init>(Context.java:234)
        at org.scijava.Context.<init>(Context.java:131)
        at org.scijava.Context.<init>(Context.java:118)
        at org.scijava.Context.<init>(Context.java:107)
        at org.scijava.jupyter.kernel.ScijavaKernel.main(ScijavaKernel.java:105)
Caused by: java.lang.UnsatisfiedLinkError: no SimpleITKJava in java.library.path
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
        at java.lang.Runtime.loadLibrary0(Runtime.java:870)
        at java.lang.System.loadLibrary(System.java:1122)
        at net.imagej.itk.DefaultImageJItkService.initialize(DefaultImageJItkService.java:87)
        at org.scijava.service.ServiceHelper.createServiceRecursively(ServiceHelper.java:353)
        at org.scijava.service.ServiceHelper.createExactService(ServiceHelper.java:269)
        ... 9 more```

**Comment by hadim** [comment]
It looks like the `DefaultImageJItkService` is not loaded but I don;t understand why is this service necessary.

Could you try with a clean Fiji installation @geekSiddharth 

@ctrueden something to do with headless mode?

**Comment by hadim** [comment]
@geekSiddharth installation from inside Fiji is not supported anymore. I would suggest you follow the official installation process using Anaconda (see the README).

If you have more questions, please ask here or open a new issue.
