### ISSUE TITLE
When I try to start Jupyter notebook with your Java kernel I receive the error described below

### ISSUE THREAD

**Issue by BerzhanKurmanov** [scijava/scijava-jupyter-kernel#98]
(java_env) C:\Users\b.kurmanov>jupyter notebook
Traceback (most recent call last):
  File "C:\Users\b.kurmanov\AppData\Local\Continuum\anaconda3\envs\java_env\Scripts\jupyter-notebook-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\Users\b.kurmanov\AppData\Local\Continuum\anaconda3\envs\java_env\lib\site-packages\jupyter_core\application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "C:\Users\b.kurmanov\AppData\Local\Continuum\anaconda3\envs\java_env\lib\site-packages\traitlets\config\application.py", line 663, in launch_instance
    app.initialize(argv)
  File "<C:\Users\b.kurmanov\AppData\Local\Continuum\anaconda3\envs\java_env\lib\site-packages\decorator.py:decorator-gen-7>", line 2, in initialize
  File "C:\Users\b.kurmanov\AppData\Local\Continuum\anaconda3\envs\java_env\lib\site-packages\traitlets\config\application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "C:\Users\b.kurmanov\AppData\Local\Continuum\anaconda3\envs\java_env\lib\site-packages\notebook\notebookapp.py", line 1679, in initialize
    self.init_webapp()
  File "C:\Users\b.kurmanov\AppData\Local\Continuum\anaconda3\envs\java_env\lib\site-packages\notebook\notebookapp.py", line 1442, in init_webapp
    self.http_server.listen(port, self.ip)
  File "C:\Users\b.kurmanov\AppData\Local\Continuum\anaconda3\envs\java_env\lib\site-packages\tornado\tcpserver.py", line 152, in listen
    self.add_sockets(sockets)
  File "C:\Users\b.kurmanov\AppData\Local\Continuum\anaconda3\envs\java_env\lib\site-packages\tornado\tcpserver.py", line 165, in add_sockets
    self._handlers[sock.fileno()] = add_accept_handler(
  File "C:\Users\b.kurmanov\AppData\Local\Continuum\anaconda3\envs\java_env\lib\site-packages\tornado\netutil.py", line 279, in add_accept_handler
    io_loop.add_handler(sock, accept_handler, IOLoop.READ)
  File "C:\Users\b.kurmanov\AppData\Local\Continuum\anaconda3\envs\java_env\lib\site-packages\tornado\platform\asyncio.py", line 99, in add_handler
    self.asyncio_loop.add_reader(fd, self._handle_events, fd, IOLoop.READ)
  File "C:\Users\b.kurmanov\AppData\Local\Continuum\anaconda3\envs\java_env\lib\asyncio\events.py", line 501, in add_reader
    raise NotImplementedError
NotImplementedError

How can I fix it?

**Comment by jetilton** [comment]
I receive the same error

```
(java_env) C:\Users\G0PDWJPT>jupyter notebook
Traceback (most recent call last):
  File "C:\Anaconda3\envs\java_env\Scripts\jupyter-notebook-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\Anaconda3\envs\java_env\lib\site-packages\jupyter_core\application.py", line 268, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "C:\Anaconda3\envs\java_env\lib\site-packages\traitlets\config\application.py", line 663, in launch_instance
    app.initialize(argv)
  File "<C:\Anaconda3\envs\java_env\lib\site-packages\decorator.py:decorator-gen-7>", line 2, in initialize
  File "C:\Anaconda3\envs\java_env\lib\site-packages\traitlets\config\application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "C:\Anaconda3\envs\java_env\lib\site-packages\notebook\notebookapp.py", line 1679, in initialize
    self.init_webapp()
  File "C:\Anaconda3\envs\java_env\lib\site-packages\notebook\notebookapp.py", line 1442, in init_webapp
    self.http_server.listen(port, self.ip)
  File "C:\Anaconda3\envs\java_env\lib\site-packages\tornado\tcpserver.py", line 152, in listen
    self.add_sockets(sockets)
  File "C:\Anaconda3\envs\java_env\lib\site-packages\tornado\tcpserver.py", line 165, in add_sockets
    self._handlers[sock.fileno()] = add_accept_handler(
  File "C:\Anaconda3\envs\java_env\lib\site-packages\tornado\netutil.py", line 279, in add_accept_handler
    io_loop.add_handler(sock, accept_handler, IOLoop.READ)
  File "C:\Anaconda3\envs\java_env\lib\site-packages\tornado\platform\asyncio.py", line 99, in add_handler
    self.asyncio_loop.add_reader(fd, self._handle_events, fd, IOLoop.READ)
  File "C:\Anaconda3\envs\java_env\lib\asyncio\events.py", line 501, in add_reader
    raise NotImplementedError
NotImplementedError
```

**Comment by dtschuler** [comment]
Don't use the approved reply, use the other one further down. 
https://stackoverflow.com/questions/58422817/jupyter-notebook-with-python-3-8-notimplementederror

This worked for me on Python 3.7 as well. Just make sure to modify the asyncio init file in your venv. For me on my weird pc it was in  C:\Users\dschuler\AppData\Local\Continuum\miniconda3\envs\java_env\Lib\asyncio\__init__.py

**Comment by ctrueden** [comment]
The scijava-jupyter-kernel project is being retired in favor of other solutions like [IJava](https://github.com/SpencerPark/IJava) and [BeakerX](http://beakerx.com).
