### ISSUE TITLE
Java8 Streams not available?

### ISSUE THREAD

**Issue by diyoyo** [scijava/scijava-jupyter-kernel#99]
Hi, I just discovered sciJava-jupyter and I am really excited about it.
Yet, this simple code failed

```
import java.util.stream.IntStream;

IntStream.range(0, 100).mapToObj(i->"Line "+i).forEach(System.out::println);
```

with the following error:

```
[ERROR] null
org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
Script1.groovy: 3: unexpected token: -> @ line 3, column 38.
   IntStream.range(0, 100).mapToObject(i->"Line "+i).forEach(System.out::println);
                                        ^

1 error

	at org.codehaus.groovy.control.ErrorCollector.failIfErrors(ErrorCollector.java:310)
	at org.codehaus.groovy.control.ErrorCollector.addFatalError(ErrorCollector.java:150)
	at org.codehaus.groovy.control.ErrorCollector.addError(ErrorCollector.java:120)
	at org.codehaus.groovy.control.ErrorCollector.addError(ErrorCollector.java:132)
	at org.codehaus.groovy.control.SourceUnit.addError(SourceUnit.java:350)
	at org.codehaus.groovy.antlr.AntlrParserPlugin.transformCSTIntoAST(AntlrParserPlugin.java:144)
	at org.codehaus.groovy.antlr.AntlrParserPlugin.parseCST(AntlrParserPlugin.java:110)
	at org.codehaus.groovy.control.SourceUnit.parse(SourceUnit.java:234)
	at org.codehaus.groovy.control.CompilationUnit$1.call(CompilationUnit.java:168)
	at org.codehaus.groovy.control.CompilationUnit.applyToSourceUnits(CompilationUnit.java:943)
	at org.codehaus.groovy.control.CompilationUnit.doPhaseOperation(CompilationUnit.java:605)
	at org.codehaus.groovy.control.CompilationUnit.processPhaseOperations(CompilationUnit.java:581)
	at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:558)
	at groovy.lang.GroovyClassLoader.doParseClass(GroovyClassLoader.java:298)
	at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:268)
	at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:254)
	at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:250)
	at org.scijava.plugins.scripting.groovy.GroovyScriptEngine.getScriptClass(GroovyScriptEngine.java:319)
	at org.scijava.plugins.scripting.groovy.GroovyScriptEngine.eval(GroovyScriptEngine.java:122)
	at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)
	at org.scijava.script.ScriptModule.run(ScriptModule.java:160)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:168)
	at org.scijava.jupyter.kernel.evaluator.Worker.run(Worker.java:108)
	at org.scijava.thread.DefaultThreadService$2.run(DefaultThreadService.java:221)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

Is that normal?,

Thanks.

**Comment by imagejan** [comment]
You seem to be running a notebook with Groovy kernel. The syntax for Groovy closures is different from Java lambdas. The following should work:

```
import java.util.stream.IntStream;

IntStream.range(0, 100).mapToObj({i->"Line "+i}).forEach({println(it)});
```

Note that `scijava-jupyter-kernel` is basically obsolete, at least the SciJava and ImageJ projects rely on the BeakerX kernel now.

**Comment by diyoyo** [comment]
Thanks, 
I actually had not realized that this was not compatible with Java.
I'll search for BeakerX and see if this is Java friendly.
Cheers,
